name: Manual Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      app-image:
        description: 'Location'
        required: false
        default: 'San Francisco, CA'

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: |
          echo "Hello ${{ github.event.inputs.app-name }}"
          echo "Home: ${{ github.event.inputs.app-image }}"
