name: 'Terraform - deploy'

on:
  push:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
  az-login:
    needs: [checkout]
    runs-on: ubuntu-latest
    steps:
      - name: az login
        run: |
          echo "Logging in to Azure using Service Principal credentials.."
          az login --service-principal -u b3cd955f-8544-41d2-aee4-7e0cb6a5bd2d -p xuy8Q~Ktm3VVRtO~5aTB3Cu6Jp3KUI6O7Ftroazx --tenant 5ce5fed3-0a25-4f4d-8697-e4b70519b7f2 
          echo "Login complete "
          az account set --subscription 79b014ea-6a1a-4930-9818-fddc78b6ce5c

        

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
  terraform-init:
    needs: [checkout, az-login]
    runs-on: ubuntu-latest
    steps:
      - name: Terraform init
        working-directory: hh
        run: terraform init

  terraform-plan:
    needs: [checkout, az-login, terraform-init]
    runs-on: ubuntu-latest
    steps:
      - name: Terraform plan
        working-directory: hh
        run: terraform plan -input=false

  terraform-apply:
    needs: [checkout, az-login, terraform-init, terraform-plan]
    runs-on: ubuntu-latest
    steps:
      - name: Terraform apply
        working-directory: hh
        run: terraform apply -input=false -auto-approve
